#!/bin/bash
#
# curl api call tests
#
# options:
#
# -v verbose
# -i Include protocol headers in the output (H/F)
#
# use -X POST for post requests
#
# -L is generally needed to follow redirects
#
#

. api-config

echo
echo "GET product by article number"
echo

curl -Li "${BASE_URL}/index.php?option=com_api&app=kivishop&resource=article&format=raw&anum=${ARTICLE_NUMBER}" \
    --header "$AUTH_HEADER"

echo
echo
