#!/bin/bash
#
# curl api call tests
#
# options:
#
# -v verbose
# -i Include protocol headers in the output (H/F)
#
# use -X POST for post requests
#
# -L is generally needed to follow redirects
#
#

. api-config

echo
echo "POST new product"
echo

curl -Li -X POST "${BASE_URL}/index.php?option=com_api&app=kivishop&resource=article&format=raw&anum=009999" \
    --header "$AUTH_HEADER" \
    --data "param1=value123"

echo
echo
